"""数据模型"""
from enum import Enum
from pydantic import BaseModel, Field
from typing import Optional, Dict, List, Any
from datetime import datetime
import uuid


class ErrorType(str, Enum):
    """LLM 错误类型枚举"""
    RATE_LIMIT = "RateLimitError"
    AUTH = "AuthenticationError"
    INVALID_REQUEST = "InvalidRequestError"
    TIMEOUT = "TimeoutError"
    CONNECTION = "APIConnectionError"
    SERVER_ERROR = "InternalServerError"
    CONTENT_FILTER = "ContentFilterError"
    MODEL_OVERLOADED = "ModelOverloadedError"
    CONTEXT_LENGTH = "ContextLengthExceededError"
    QUOTA_EXCEEDED = "QuotaExceededError"
    UNKNOWN = "UnknownError"


class RetryStrategy(BaseModel):
    """重试策略"""
    suggestion: str = Field(description="建议策略")
    max_retries: int = 3
    base_delay: float = 1.0
    max_delay: float = 60.0
    backoff_factor: float = 2.0


class ErrorRecord(BaseModel):
    """错误记录"""
    error_id: str = Field(default_factory=lambda: f"err_{datetime.now().strftime('%Y%m%d_%H%M%S')}_{uuid.uuid4().hex[:8]}")
    timestamp: str = Field(default_factory=lambda: datetime.now().isoformat())
    provider: str = Field(description="API 服务商")
    error_type: ErrorType
    status_code: Optional[int] = None
    message: str
    details: Dict[str, Any] = Field(default_factory=dict)
    context: Dict[str, Any] = Field(default_factory=dict)
    tags: List[str] = Field(default_factory=list)
    root_cause: Optional[str] = None
    solution: Optional[str] = None
    retry_strategy: Optional[RetryStrategy] = None
    stack_trace: Optional[str] = None

    def to_markdown(self) -> str:
        """生成 Markdown 文档"""
        md = f"""# Error Report: {self.error_id}

## 基本信息
- **时间**: {self.timestamp}
- **服务商**: {self.provider}
- **错误类型**: {self.error_type.value}
- **状态码**: {self.status_code or 'N/A'}

## 错误信息
```
{self.message}
```

## 上下文
```json
{self._json_dumps(self.context)}
```

## 根因分析
{self.root_cause or '待分析'}

## 解决方案
{self.solution or '待分析'}

## 重试策略
{self.retry_strategy.suggestion if self.retry_strategy else '待分析'}

---
*Generated by LLM Exception Recorder*
"""
        return md

    def _json_dumps(self, data: dict) -> str:
        import json
        return json.dumps(data, indent=2, ensure_ascii=False)

    def to_dict(self) -> dict:
        return self.model_dump()


class LLMError(Exception):
    """自定义 LLM 错误"""
    def __init__(
        self,
        message: str,
        error_type: ErrorType = ErrorType.UNKNOWN,
        provider: str = "unknown",
        status_code: Optional[int] = None,
        details: Optional[Dict] = None
    ):
        super().__init__(message)
        self.error_type = error_type
        self.provider = provider
        self.status_code = status_code
        self.details = details or {}


class ErrorStats(BaseModel):
    """错误统计"""
    total_errors: int = 0
    by_type: Dict[str, int] = Field(default_factory=dict)
    by_provider: Dict[str, int] = Field(default_factory=dict)
    by_day: Dict[str, int] = Field(default_factory=dict)
    avg_response_time: Optional[float] = None
    error_rate: Optional[float] = None
    top_errors: List[Dict] = Field(default_factory=list)

    def to_markdown(self) -> str:
        md = f"""# LLM 错误统计报告

## 概览
- **总错误数**: {self.total_errors}
- **平均响应时间**: {self.avg_response_time:.2f}s if self.avg_response_time else 'N/A'
- **错误率**: {self.error_rate*100:.1f}% if self.error_rate else 'N/A'

## 按类型分布
"""
        for error_type, count in sorted(self.by_type.items(), key=lambda x: -x[1]):
            md += f"- {error_type}: {count}\n"

        md += "\n## 按服务商分布\n"
        for provider, count in sorted(self.by_provider.items(), key=lambda x: -x[1]):
            md += f"- {provider}: {count}\n"

        return md
